### ISSUE TITLE
Download exception

### ISSUE THREAD

**Issue by dakahler** [vikas5914/google-photos-backup#7]
Got this error with latest

`Download Complete: 2013/6/IMG_3309.jpg
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at ReadTask.for (/home/unraid/google-photos-backup/node_modules/exiftool-vendored/dist/ReadTask.js:115:34)
    at /home/unraid/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:170:62
    at f (/home/unraid/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:355:29)
    at async g (/home/unraid/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by christophershad** [comment]
node:path:1210
      validateString(path, `paths[${i}]`);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null
    at Object.resolve (node:path:1210:7)
    at ReadTask.for (/media/gphotos/Takeout_Photos_01/google-photos-backup/node_modules/exiftool-vendored/dist/ReadTask.js:107:34)
    at /media/gphotos/Takeout_Photos_01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:147:62
    at f (/media/gphotos/Takeout_Photos_01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:330:29)
    at g (/media/gphotos/Takeout_Photos_01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:26)
    at g (/media/gphotos/Takeout_Photos_01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:24)
    at async downloadPhoto (file:///media/gphotos/Takeout_Photos_01/google-photos-backup/index.js:170:20)
    at async file:///media/gphotos/Takeout_Photos_01/google-photos-backup/index.js:144:5 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.19.4
gphotos@gphotos-VMware-Virtual-Platform:/media/gphotos/Takeout_Photos_01/google-photos-backup$ 


I receive this error fairly regularly. If I run it again it picks up where it left off and continues. How can I prevent this?

**Comment by vikas5914** [comment]
@christophershad Will look into this..

**Comment by christophershad** [comment]
Ok, just made a whole new machine using Ubuntu 24.04, different hardware, different OS version, using Chrome instead of Chromium, etc. Ran for about 2 hours then a very similar error:
Download Complete: 2013/9/ContactPhoto-IMG_20130927_173044.jpg
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at ReadTask.for (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ReadTask.js:107:34)
    at /home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:147:62
    at f (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:330:29)
    at g (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:26)
    at g (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:24)
    at async downloadPhoto (file:///home/gphotos01/google-photos-backup/index.js:170:20)
    at async file:///home/gphotos01/google-photos-backup/index.js:144:5 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.1
gphotos01@gphotos01-virt:~/google-photos-backup$

After this I started it again and it picked up where it left off.

**Comment by christophershad** [comment]
Download Complete: [obscured].jpg
^Cnode:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at ReadTask.for (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ReadTask.js:107:34)
    at /home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:147:62
    at f (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/ExifTool.js:330:29)
    at g (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:26)
    at g (/home/gphotos01/google-photos-backup/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:24)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.1
gphotos01@gphotos01-virt:~/google-photos-backup$ 

This is still continuing, across multiple computers with varied Ubuntu operating systems. The above error message was generated by doing a CTRL+C in the terminal, not naturally generated. I thought it was interesting that just a generic Interrupt produced this similar message. Is it just terminating for some other reason?
